trigger:
- master

pool:
  vmImage: ubuntu-latest

steps:
- checkout: self
  persistCredentials: true

- script: |
   git config --global user.email pipeline@demo.com & git config --global user.name "Pipeline"
  workingDirectory: $(System.DefaultWorkingDirectory)

- script: |
   git checkout -b master
   echo 'This is a test' > data.txt
   git add -A
   git commit -m "deployment $(Build.BuildNumber)"
   git push --set-upstream origin master 
  displayName: Add data.txt file
  workingDirectory: $(System.DefaultWorkingDirectory)